[package]
name = "fib_rs"
version = "0.1.0"
authors = ["ssshikari <ssshikari@gmail.com>"]
edition = "2021"

[dependencies]


[lib]
name = "fib_rs"
crate-type=["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
